//@ui5-bundle com/idom/zxrouterbtp/Component-preload.js
jQuery.sap.registerPreloadedModules({
"version":"2.0",
"modules":{
	"com/idom/zxrouterbtp/Component.js":function(){sap.ui.define(["sap/ui/core/UIComponent","sap/ui/Device","com/idom/zxrouterbtp/model/models"],function(e,i,a){"use strict";return e.extend("com.idom.zxrouterbtp.Component",{metadata:{manifest:"json"},init:function(){e.prototype.init.apply(this,arguments);this.getRouter().initialize();this.setModel(a.createDeviceModel(),"device");var i="";var t="";var s="";var r=jQuery.sap.getUriParameters().get("sap-language");if(!r){r=window["sap-ushell-config"].startupConfig.language}if(jQuery.sap.getUriParameters().get("IsClient")||window.location.hash.indexOf("IsClient")>0){if(jQuery.sap.getUriParameters().get("IsClient")){i=jQuery.sap.getUriParameters().get("IsClient")}else{i=window.location.hash.substring(window.location.hash.indexOf("IsClient"));i=this.getUrlParameter(i,"IsClient")}}if(jQuery.sap.getUriParameters().get("IdApp")||window.location.hash.indexOf("IdApp")>0){if(jQuery.sap.getUriParameters().get("IdApp")){t=jQuery.sap.getUriParameters().get("IdApp")}else{t=window.location.hash.substring(window.location.hash.indexOf("IdApp"));t=this.getUrlParameter(t,"IdApp")}if(t){var o=".dispatcher.eu3.hana.ondemand.com",n="c3563wjipz",p="zn8v2t19df",l="s7e5f2f6b",d="https://"+t+"-";if(window.location.href.indexOf("erp.idom.com")>=0){d=d+l+o}else if(window.location.href.indexOf("sapqas.idom.com")>=0){d=d+p+o}else{d=d+n+o}if(i.length>0){o=".idom.com:4300/#/";if(r.toUpperCase()==="ES"){o=o+"es/"}else{o=o+"en/"}n="sapspdev";p="sapspqas";l="sapspprd";t=t.replaceAll("%20","/");if(window.location.href.indexOf("erp.idom.com")>=0){d="https://"+l+o+t}else if(window.location.href.indexOf("sapqas.idom.com")>=0){d="https://"+p+o+t}else{d="https://"+n+o+t}}window.location.replace(d)}}if(jQuery.sap.getUriParameters().get("IsAriba")||window.location.hash.indexOf("IsAriba")>0){d="";if(jQuery.sap.getUriParameters().get("IsAriba")){s=jQuery.sap.getUriParameters().get("IsAriba")}else{s=window.location.hash.substring(window.location.hash.indexOf("IsAriba"));s=this.getUrlParameter(s,"IsAriba")}if(window.location.href.indexOf("erp.idom.com")>=0){d="https://"+"s1-eu.ariba.com/Sourcing/Main/ad/loginPage/SSOActions?awsso_ap=ACM&realm=idom&awsr=true"}else if(window.location.href.indexOf("sapqas.idom.com")>=0){d="https://"+"s1-eu.ariba.com/Sourcing/Main/ad/loginPage/SSOActions?awsso_ap=ACM&realm=idom-t&awsr=true"}else{alert("No es posible acceder a la aplicación")}window.location.replace(d)}},getUrlParameter:function(e,i){var a=e.split("&");for(var t=0;t<a.length;t++){var s=a[t].split("=");if(s[0]==i){return s[1]}}return false}})});
},
	"com/idom/zxrouterbtp/controller/App.controller.js":function(){sap.ui.define(["sap/ui/core/mvc/Controller"],function(n){"use strict";return n.extend("com.idom.zxrouterbtp.controller.App",{onInit:function(){}})});
},
	"com/idom/zxrouterbtp/controller/BaseController.js":function(){sap.ui.define(["sap/ui/core/mvc/Controller","sap/ui/core/routing/History","sap/m/MessageBox","sap/ui/model/json/JSONModel"],function(e,t,n,o){"use strict";var i="com.idom.zxrouterbtp";return e.extend(i+".controller.BaseController",{getRouter:function(){return this.getOwnerComponent().getRouter()},getModel:function(e){return this.getView().getModel(e)},setModel:function(e,t){return this.getView().setModel(e,t)},getResourceBundle:function(){return this.getOwnerComponent().getModel("i18n").getResourceBundle()},getI18n:function(){return this.getResourceBundle()},onNavBack:function(){var e=t.getInstance().getPreviousHash();var n;if(sap.ushell&&sap.ushell.Container){n=sap.ushell.Container.getService("CrossApplicationNavigation")}if(e!==undefined||n&&!n.isInitialNavigation()){history.go(-1)}else{if(n){n.toExternal({target:{semanticObject:"Shell",action:"home"}})}}}})});
},
	"com/idom/zxrouterbtp/controller/Main.controller.js":function(){sap.ui.define(["./BaseController","sap/m/MessageBox"],function(e,t){"use strict";return e.extend("com.idom.zxrouterbtp.controller.Main",{onInit:function(){this.getRouter().getRoute("RouteMain").attachPatternMatched(this._onViewMatched,this)},_onViewMatched:function(e){var a="";var r=jQuery.sap.getUriParameters().get("sap-language");if(!r){r=window["sap-ushell-config"].startupConfig.language}if(e.getParameter("arguments")&&e.getParameter("arguments").IsClient||jQuery.sap.getUriParameters().get("IsClient")||window.location.hash.indexOf("IsClient")>0){if(e.getParameter("arguments")&&e.getParameter("arguments").IsClient){a=e.getParameter("arguments").IsClient}else if(jQuery.sap.getUriParameters().get("IsClient")){a=jQuery.sap.getUriParameters().get("IsClient")}else{a=window.location.hash.substring(window.location.hash.indexOf("IsClient"));a=this.getUrlParameter(a,"IsClient")}}if(e.getParameter("arguments")&&e.getParameter("arguments").IdApp||jQuery.sap.getUriParameters().get("IdApp")||window.location.hash.indexOf("IdApp")>0){var i="";if(e.getParameter("arguments")&&e.getParameter("arguments").IdApp){i=e.getParameter("arguments").IdApp}else if(jQuery.sap.getUriParameters().get("IdApp")){i=jQuery.sap.getUriParameters().get("IdApp")}else{i=window.location.hash.substring(window.location.hash.indexOf("IdApp"));i=this.getUrlParameter(i,"IdApp")}var s=".dispatcher.eu3.hana.ondemand.com",n="c3563wjipz",o="zn8v2t19df",p="s7e5f2f6b",g="";if(window.location.href.indexOf("erp.idom.com")>=0){g="https://"+i+"-"+p+s}else if(window.location.href.indexOf("sapqas.idom.com")>=0){g="https://"+i+"-"+o+s}else{g="https://"+i+"-"+n+s}if(a.length>0){s=".idom.com:4300/#/";if(r.toUpperCase()==="ES"){s=s+"es/"}else{s=s+"en/"}n="sapspdev";o="sapspqas";p="sapspprd";i=i.replaceAll("%20","/");if(window.location.href.indexOf("erp.idom.com")>=0){g="https://"+p+s+i}else if(window.location.href.indexOf("sapqas.idom.com")>=0){g="https://"+o+s+i}else{g="https://"+n+s+i}}window.location.replace(g)}else{t.error(this.getI18n().getText("errorOpenApp"),{onClose:function(){this.onNavBack()}.bind(this)})}},getUrlParameter:function(e,t){var a=e.split("&");for(var r=0;r<a.length;r++){var i=a[r].split("=");if(i[0]==t){return i[1]}}return false}})});
},
	"com/idom/zxrouterbtp/i18n/i18n.properties":'title=Title\nappTitle=zxrouterbtp\nappDescription=App Description\nerrorOpenApp=Error al abrir la aplicaci\\u00f3n, Comun\\u00edquese con el administrador del sistema.',
	"com/idom/zxrouterbtp/manifest.json":'{"_version":"1.12.0","sap.app":{"id":"com.idom.zxrouterbtp","type":"application","i18n":"i18n/i18n.properties","applicationVersion":{"version":"1.0.0"},"title":"{{appTitle}}","description":"{{appDescription}}","sourceTemplate":{"id":"ui5template.basicSAPUI5ApplicationProject","version":"1.38.11"}},"sap.ui":{"technology":"UI5","icons":{"icon":"","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"flexEnabled":false,"rootView":{"viewName":"com.idom.zxrouterbtp.view.App","type":"XML","async":true},"dependencies":{"minUI5Version":"1.65.6","libs":{"sap.ui.layout":{},"sap.ui.core":{},"sap.m":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"com.idom.zxrouterbtp.i18n.i18n"}}},"resources":{"css":[{"uri":"css/style.css"}]},"routing":{"config":{"routerClass":"sap.m.routing.Router","viewType":"XML","async":true,"viewPath":"com.idom.zxrouterbtp.view","controlAggregation":"pages","controlId":"app","clearControlAggregation":false},"routes":[{"name":"RouteMain","pattern":"","target":["TargetMain"]}],"targets":{"TargetMain":{"viewType":"XML","transition":"slide","clearControlAggregation":false,"viewName":"Main"}}}},"sap.platform.abap":{"uri":"/sap/bc/ui5_ui5/sap/zxrouterapp/webapp","_version":"1.1.0"}}',
	"com/idom/zxrouterbtp/model/models.js":function(){sap.ui.define(["sap/ui/model/json/JSONModel","sap/ui/Device"],function(e,n){"use strict";return{createDeviceModel:function(){var i=new e(n);i.setDefaultBindingMode("OneWay");return i}}});
},
	"com/idom/zxrouterbtp/view/App.view.xml":'<mvc:View xmlns:core="sap.ui.core" xmlns:mvc="sap.ui.core.mvc" xmlns="sap.m" controllerName="com.idom.zxrouterbtp.controller.App"\n\txmlns:html="http://www.w3.org/1999/xhtml"><App id="app"></App></mvc:View>',
	"com/idom/zxrouterbtp/view/Main.view.xml":'<mvc:View controllerName="com.idom.zxrouterbtp.controller.Main" xmlns:mvc="sap.ui.core.mvc" displayBlock="true" xmlns="sap.m"><Shell id="shell"><Page id="page" title="{i18n>title}"><content></content></Page></Shell></mvc:View>'
}});
